import { Sometype_Mono } from "next/font/google";
import "./globals.css";
// components
import MainNav from "@/components/MainNav";
import PageTrainsition from "@/components/PageTrainsition";
import RectangleTransition from "@/components/RectangleTransition";

const sometypeMono = Sometype_Mono({
  variable: "--font-sometypeMono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sometypeMono.variable} antialiased overflow-hidden relative`}>
        <RectangleTransition />
        <PageTrainsition>
          <div className="flex">
            {/* Main Nav */}
            <div className="hidden 2xl:flex w-[285px] h-screen bg-secondary">
              <MainNav />
            </div>
            {/* MainContainer */}
            <main className="w-full max-w-[1130px] px-[15px] mx-auto ">
              <header>header</header>
              <div>{children}</div>
            </main>
          </div>
        </PageTrainsition>
      </body>
    </html>
  );
}
